export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SESSION_LOGIN_SUCCESSFUL = 'SESSION_LOGIN_SUCCESSFUL';
export const REGISTER_DRIVER = 'REGISTER_DRIVER';
export const CLEAR_AUTH = 'CLEAR_AUTH';